In [56]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [43]:
df=pd.read_csv(r'P:\titanic\Titanic-Dataset.csv')

In [44]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [55]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='str')

In [45]:
df.drop(columns=["PassengerId", "Name", "Ticket","Cabin"], inplace=True)

In [46]:
df.sample()

     Survived  Pclass   Sex   Age  SibSp  Parch   Fare Embarked
675         0       3  male  18.0      0      0  7.775        S

In [47]:
y = df["Survived"]
X = df.drop("Survived",axis=1)

In [48]:
num_val = ["Pclass","Age","SibSp","Parch","Fare"]
col_val =["Sex","Embarked"]

In [49]:
#making num pipeline

num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean"))
])
# Categorical pipeline
cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(
        sparse_output=False,
        handle_unknown="ignore"
    ))
])

In [50]:
#combinng both pipeline 
preprocesser = ColumnTransformer([
   ( 'num',num_pipeline,num_val),
   ('cat',cat_pipeline,col_val)

])

In [51]:

# Complete ML pipeline
model_pipeline = Pipeline([
    ("preprocessing", preprocesser),
    ("model", RandomForestClassifier(random_state=42))
])

In [52]:
# Split data
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42
)

In [53]:
# Train
model_pipeline.fit(X_train, y_train)


# Predict
y_pred = model_pipeline.predict(X_test)


# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8156424581005587

In [57]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1:", f1)

Accuracy: 0.8156424581005587
Precision: 0.7971014492753623
Recall: 0.7432432432432432
F1: 0.7692307692307693